// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func AddressValidate(obj *Address) []error {
	var errs []error

	if !(obj.Street != "") {
		errs = append(errs, types.NewValidationError("Street is required"))
	}

	if !(obj.City != "") {
		errs = append(errs, types.NewValidationError("City is required"))
	}

	return errs
}
