// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func AllTypes1Validate(obj *AllTypes1) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.LastName != "") {
		errs = append(errs, types.NewValidationError("LastName is required"))
	}

	if !(obj.Age != 0) {
		errs = append(errs, types.NewValidationError("Age is required"))
	}

	return errs
}
