// Code generated by TestGen. DO NOT EDIT.

package main

import (
	"log"
)

func innerFieldnoPointerTests() {
	eqfieldStructFieldsTests()
	neqfieldStructFieldsTests()
	gtfieldStructFieldsTests()
	gtefieldStructFieldsTests()
	ltfieldStructFieldsTests()
	ltefieldStructFieldsTests()

}

type eqfieldStructFields struct {
	Field1EqfieldString  string `valid:"eqfield=Field2EqfieldString"`
	Field2EqfieldString  string
	Field1EqfieldInt     int `valid:"eqfield=Field2EqfieldInt"`
	Field2EqfieldInt     int
	Field1EqfieldInt8    int8 `valid:"eqfield=Field2EqfieldInt8"`
	Field2EqfieldInt8    int8
	Field1EqfieldInt16   int16 `valid:"eqfield=Field2EqfieldInt16"`
	Field2EqfieldInt16   int16
	Field1EqfieldInt32   int32 `valid:"eqfield=Field2EqfieldInt32"`
	Field2EqfieldInt32   int32
	Field1EqfieldInt64   int64 `valid:"eqfield=Field2EqfieldInt64"`
	Field2EqfieldInt64   int64
	Field1EqfieldUint    uint `valid:"eqfield=Field2EqfieldUint"`
	Field2EqfieldUint    uint
	Field1EqfieldUint8   uint8 `valid:"eqfield=Field2EqfieldUint8"`
	Field2EqfieldUint8   uint8
	Field1EqfieldUint16  uint16 `valid:"eqfield=Field2EqfieldUint16"`
	Field2EqfieldUint16  uint16
	Field1EqfieldUint32  uint32 `valid:"eqfield=Field2EqfieldUint32"`
	Field2EqfieldUint32  uint32
	Field1EqfieldUint64  uint64 `valid:"eqfield=Field2EqfieldUint64"`
	Field2EqfieldUint64  uint64
	Field1EqfieldFloat32 float32 `valid:"eqfield=Field2EqfieldFloat32"`
	Field2EqfieldFloat32 float32
	Field1EqfieldFloat64 float64 `valid:"eqfield=Field2EqfieldFloat64"`
	Field2EqfieldFloat64 float64
	Field1EqfieldBool    bool `valid:"eqfield=Field2EqfieldBool"`
	Field2EqfieldBool    bool
}

func eqfieldStructFieldsTests() {
	log.Println("starting eqfieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &eqfieldStructFields{}
	expectedMsgErrors = []string{
		"Field1EqfieldString must be equal to Field2EqfieldString",
		"Field1EqfieldInt must be equal to Field2EqfieldInt",
		"Field1EqfieldInt8 must be equal to Field2EqfieldInt8",
		"Field1EqfieldInt16 must be equal to Field2EqfieldInt16",
		"Field1EqfieldInt32 must be equal to Field2EqfieldInt32",
		"Field1EqfieldInt64 must be equal to Field2EqfieldInt64",
		"Field1EqfieldUint must be equal to Field2EqfieldUint",
		"Field1EqfieldUint8 must be equal to Field2EqfieldUint8",
		"Field1EqfieldUint16 must be equal to Field2EqfieldUint16",
		"Field1EqfieldUint32 must be equal to Field2EqfieldUint32",
		"Field1EqfieldUint64 must be equal to Field2EqfieldUint64",
		"Field1EqfieldFloat32 must be equal to Field2EqfieldFloat32",
		"Field1EqfieldFloat64 must be equal to Field2EqfieldFloat64",
		"Field1EqfieldBool must be equal to Field2EqfieldBool",
	}

	v.Field1EqfieldString = "fghij"
	v.Field1EqfieldInt = 64
	v.Field1EqfieldInt8 = 64
	v.Field1EqfieldInt16 = 64
	v.Field1EqfieldInt32 = 64
	v.Field1EqfieldInt64 = 64
	v.Field1EqfieldUint = 64
	v.Field1EqfieldUint8 = 64
	v.Field1EqfieldUint16 = 64
	v.Field1EqfieldUint32 = 64
	v.Field1EqfieldUint64 = 64
	v.Field1EqfieldFloat32 = 34.56
	v.Field1EqfieldFloat64 = 34.56
	v.Field1EqfieldBool = false

	errs = eqfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &eqfieldStructFields{}
	v.Field1EqfieldString = "abcde"
	v.Field1EqfieldInt = 32
	v.Field1EqfieldInt8 = 32
	v.Field1EqfieldInt16 = 32
	v.Field1EqfieldInt32 = 32
	v.Field1EqfieldInt64 = 32
	v.Field1EqfieldUint = 32
	v.Field1EqfieldUint8 = 32
	v.Field1EqfieldUint16 = 32
	v.Field1EqfieldUint32 = 32
	v.Field1EqfieldUint64 = 32
	v.Field1EqfieldFloat32 = 12.34
	v.Field1EqfieldFloat64 = 12.34
	v.Field1EqfieldBool = true

	expectedMsgErrors = nil
	errs = eqfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("eqfieldStructFields types tests ok")
}

type neqfieldStructFields struct {
	Field1NeqfieldString  string `valid:"neqfield=Field2NeqfieldString"`
	Field2NeqfieldString  string
	Field1NeqfieldInt     int `valid:"neqfield=Field2NeqfieldInt"`
	Field2NeqfieldInt     int
	Field1NeqfieldInt8    int8 `valid:"neqfield=Field2NeqfieldInt8"`
	Field2NeqfieldInt8    int8
	Field1NeqfieldInt16   int16 `valid:"neqfield=Field2NeqfieldInt16"`
	Field2NeqfieldInt16   int16
	Field1NeqfieldInt32   int32 `valid:"neqfield=Field2NeqfieldInt32"`
	Field2NeqfieldInt32   int32
	Field1NeqfieldInt64   int64 `valid:"neqfield=Field2NeqfieldInt64"`
	Field2NeqfieldInt64   int64
	Field1NeqfieldUint    uint `valid:"neqfield=Field2NeqfieldUint"`
	Field2NeqfieldUint    uint
	Field1NeqfieldUint8   uint8 `valid:"neqfield=Field2NeqfieldUint8"`
	Field2NeqfieldUint8   uint8
	Field1NeqfieldUint16  uint16 `valid:"neqfield=Field2NeqfieldUint16"`
	Field2NeqfieldUint16  uint16
	Field1NeqfieldUint32  uint32 `valid:"neqfield=Field2NeqfieldUint32"`
	Field2NeqfieldUint32  uint32
	Field1NeqfieldUint64  uint64 `valid:"neqfield=Field2NeqfieldUint64"`
	Field2NeqfieldUint64  uint64
	Field1NeqfieldFloat32 float32 `valid:"neqfield=Field2NeqfieldFloat32"`
	Field2NeqfieldFloat32 float32
	Field1NeqfieldFloat64 float64 `valid:"neqfield=Field2NeqfieldFloat64"`
	Field2NeqfieldFloat64 float64
	Field1NeqfieldBool    bool `valid:"neqfield=Field2NeqfieldBool"`
	Field2NeqfieldBool    bool
}

func neqfieldStructFieldsTests() {
	log.Println("starting neqfieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &neqfieldStructFields{}
	expectedMsgErrors = []string{
		"Field1NeqfieldString must not be equal to Field2NeqfieldString",
		"Field1NeqfieldInt must not be equal to Field2NeqfieldInt",
		"Field1NeqfieldInt8 must not be equal to Field2NeqfieldInt8",
		"Field1NeqfieldInt16 must not be equal to Field2NeqfieldInt16",
		"Field1NeqfieldInt32 must not be equal to Field2NeqfieldInt32",
		"Field1NeqfieldInt64 must not be equal to Field2NeqfieldInt64",
		"Field1NeqfieldUint must not be equal to Field2NeqfieldUint",
		"Field1NeqfieldUint8 must not be equal to Field2NeqfieldUint8",
		"Field1NeqfieldUint16 must not be equal to Field2NeqfieldUint16",
		"Field1NeqfieldUint32 must not be equal to Field2NeqfieldUint32",
		"Field1NeqfieldUint64 must not be equal to Field2NeqfieldUint64",
		"Field1NeqfieldFloat32 must not be equal to Field2NeqfieldFloat32",
		"Field1NeqfieldFloat64 must not be equal to Field2NeqfieldFloat64",
		"Field1NeqfieldBool must not be equal to Field2NeqfieldBool",
	}

	v.Field1NeqfieldString = "abcde"
	v.Field1NeqfieldInt = 32
	v.Field1NeqfieldInt8 = 32
	v.Field1NeqfieldInt16 = 32
	v.Field1NeqfieldInt32 = 32
	v.Field1NeqfieldInt64 = 32
	v.Field1NeqfieldUint = 32
	v.Field1NeqfieldUint8 = 32
	v.Field1NeqfieldUint16 = 32
	v.Field1NeqfieldUint32 = 32
	v.Field1NeqfieldUint64 = 32
	v.Field1NeqfieldFloat32 = 12.34
	v.Field1NeqfieldFloat64 = 12.34
	v.Field1NeqfieldBool = true

	errs = neqfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &neqfieldStructFields{}
	v.Field1NeqfieldString = "fghij"
	v.Field1NeqfieldInt = 64
	v.Field1NeqfieldInt8 = 64
	v.Field1NeqfieldInt16 = 64
	v.Field1NeqfieldInt32 = 64
	v.Field1NeqfieldInt64 = 64
	v.Field1NeqfieldUint = 64
	v.Field1NeqfieldUint8 = 64
	v.Field1NeqfieldUint16 = 64
	v.Field1NeqfieldUint32 = 64
	v.Field1NeqfieldUint64 = 64
	v.Field1NeqfieldFloat32 = 34.56
	v.Field1NeqfieldFloat64 = 34.56
	v.Field1NeqfieldBool = false

	expectedMsgErrors = nil
	errs = neqfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("neqfieldStructFields types tests ok")
}

type gtfieldStructFields struct {
	Field1GtfieldInt     int `valid:"gtfield=Field2GtfieldInt"`
	Field2GtfieldInt     int
	Field1GtfieldInt8    int8 `valid:"gtfield=Field2GtfieldInt8"`
	Field2GtfieldInt8    int8
	Field1GtfieldInt16   int16 `valid:"gtfield=Field2GtfieldInt16"`
	Field2GtfieldInt16   int16
	Field1GtfieldInt32   int32 `valid:"gtfield=Field2GtfieldInt32"`
	Field2GtfieldInt32   int32
	Field1GtfieldInt64   int64 `valid:"gtfield=Field2GtfieldInt64"`
	Field2GtfieldInt64   int64
	Field1GtfieldUint    uint `valid:"gtfield=Field2GtfieldUint"`
	Field2GtfieldUint    uint
	Field1GtfieldUint8   uint8 `valid:"gtfield=Field2GtfieldUint8"`
	Field2GtfieldUint8   uint8
	Field1GtfieldUint16  uint16 `valid:"gtfield=Field2GtfieldUint16"`
	Field2GtfieldUint16  uint16
	Field1GtfieldUint32  uint32 `valid:"gtfield=Field2GtfieldUint32"`
	Field2GtfieldUint32  uint32
	Field1GtfieldUint64  uint64 `valid:"gtfield=Field2GtfieldUint64"`
	Field2GtfieldUint64  uint64
	Field1GtfieldFloat32 float32 `valid:"gtfield=Field2GtfieldFloat32"`
	Field2GtfieldFloat32 float32
	Field1GtfieldFloat64 float64 `valid:"gtfield=Field2GtfieldFloat64"`
	Field2GtfieldFloat64 float64
}

func gtfieldStructFieldsTests() {
	log.Println("starting gtfieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &gtfieldStructFields{}
	expectedMsgErrors = []string{
		"Field1GtfieldInt must be > Field2GtfieldInt",
		"Field1GtfieldInt8 must be > Field2GtfieldInt8",
		"Field1GtfieldInt16 must be > Field2GtfieldInt16",
		"Field1GtfieldInt32 must be > Field2GtfieldInt32",
		"Field1GtfieldInt64 must be > Field2GtfieldInt64",
		"Field1GtfieldUint must be > Field2GtfieldUint",
		"Field1GtfieldUint8 must be > Field2GtfieldUint8",
		"Field1GtfieldUint16 must be > Field2GtfieldUint16",
		"Field1GtfieldUint32 must be > Field2GtfieldUint32",
		"Field1GtfieldUint64 must be > Field2GtfieldUint64",
		"Field1GtfieldFloat32 must be > Field2GtfieldFloat32",
		"Field1GtfieldFloat64 must be > Field2GtfieldFloat64",
	}

	v.Field1GtfieldInt = 31
	v.Field1GtfieldInt8 = 31
	v.Field1GtfieldInt16 = 31
	v.Field1GtfieldInt32 = 31
	v.Field1GtfieldInt64 = 31
	v.Field1GtfieldUint = 31
	v.Field1GtfieldUint8 = 31
	v.Field1GtfieldUint16 = 31
	v.Field1GtfieldUint32 = 31
	v.Field1GtfieldUint64 = 31
	v.Field1GtfieldFloat32 = 12.34
	v.Field1GtfieldFloat64 = 12.34

	errs = gtfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &gtfieldStructFields{}
	v.Field1GtfieldInt = 33
	v.Field1GtfieldInt8 = 33
	v.Field1GtfieldInt16 = 33
	v.Field1GtfieldInt32 = 33
	v.Field1GtfieldInt64 = 33
	v.Field1GtfieldUint = 33
	v.Field1GtfieldUint8 = 33
	v.Field1GtfieldUint16 = 33
	v.Field1GtfieldUint32 = 33
	v.Field1GtfieldUint64 = 33
	v.Field1GtfieldFloat32 = 12.35
	v.Field1GtfieldFloat64 = 12.35

	expectedMsgErrors = nil
	errs = gtfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("gtfieldStructFields types tests ok")
}

type gtefieldStructFields struct {
	Field1GtefieldInt     int `valid:"gtefield=Field2GtefieldInt"`
	Field2GtefieldInt     int
	Field1GtefieldInt8    int8 `valid:"gtefield=Field2GtefieldInt8"`
	Field2GtefieldInt8    int8
	Field1GtefieldInt16   int16 `valid:"gtefield=Field2GtefieldInt16"`
	Field2GtefieldInt16   int16
	Field1GtefieldInt32   int32 `valid:"gtefield=Field2GtefieldInt32"`
	Field2GtefieldInt32   int32
	Field1GtefieldInt64   int64 `valid:"gtefield=Field2GtefieldInt64"`
	Field2GtefieldInt64   int64
	Field1GtefieldUint    uint `valid:"gtefield=Field2GtefieldUint"`
	Field2GtefieldUint    uint
	Field1GtefieldUint8   uint8 `valid:"gtefield=Field2GtefieldUint8"`
	Field2GtefieldUint8   uint8
	Field1GtefieldUint16  uint16 `valid:"gtefield=Field2GtefieldUint16"`
	Field2GtefieldUint16  uint16
	Field1GtefieldUint32  uint32 `valid:"gtefield=Field2GtefieldUint32"`
	Field2GtefieldUint32  uint32
	Field1GtefieldUint64  uint64 `valid:"gtefield=Field2GtefieldUint64"`
	Field2GtefieldUint64  uint64
	Field1GtefieldFloat32 float32 `valid:"gtefield=Field2GtefieldFloat32"`
	Field2GtefieldFloat32 float32
	Field1GtefieldFloat64 float64 `valid:"gtefield=Field2GtefieldFloat64"`
	Field2GtefieldFloat64 float64
}

func gtefieldStructFieldsTests() {
	log.Println("starting gtefieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &gtefieldStructFields{}
	expectedMsgErrors = []string{
		"Field1GtefieldInt must be >= Field2GtefieldInt",
		"Field1GtefieldInt8 must be >= Field2GtefieldInt8",
		"Field1GtefieldInt16 must be >= Field2GtefieldInt16",
		"Field1GtefieldInt32 must be >= Field2GtefieldInt32",
		"Field1GtefieldInt64 must be >= Field2GtefieldInt64",
		"Field1GtefieldUint must be >= Field2GtefieldUint",
		"Field1GtefieldUint8 must be >= Field2GtefieldUint8",
		"Field1GtefieldUint16 must be >= Field2GtefieldUint16",
		"Field1GtefieldUint32 must be >= Field2GtefieldUint32",
		"Field1GtefieldUint64 must be >= Field2GtefieldUint64",
		"Field1GtefieldFloat32 must be >= Field2GtefieldFloat32",
		"Field1GtefieldFloat64 must be >= Field2GtefieldFloat64",
	}

	v.Field1GtefieldInt = 31
	v.Field1GtefieldInt8 = 31
	v.Field1GtefieldInt16 = 31
	v.Field1GtefieldInt32 = 31
	v.Field1GtefieldInt64 = 31
	v.Field1GtefieldUint = 31
	v.Field1GtefieldUint8 = 31
	v.Field1GtefieldUint16 = 31
	v.Field1GtefieldUint32 = 31
	v.Field1GtefieldUint64 = 31
	v.Field1GtefieldFloat32 = 12.33
	v.Field1GtefieldFloat64 = 12.33

	errs = gtefieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &gtefieldStructFields{}
	v.Field1GtefieldInt = 32
	v.Field1GtefieldInt8 = 32
	v.Field1GtefieldInt16 = 32
	v.Field1GtefieldInt32 = 32
	v.Field1GtefieldInt64 = 32
	v.Field1GtefieldUint = 32
	v.Field1GtefieldUint8 = 32
	v.Field1GtefieldUint16 = 32
	v.Field1GtefieldUint32 = 32
	v.Field1GtefieldUint64 = 32
	v.Field1GtefieldFloat32 = 12.34
	v.Field1GtefieldFloat64 = 12.34

	expectedMsgErrors = nil
	errs = gtefieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("gtefieldStructFields types tests ok")
}

type ltfieldStructFields struct {
	Field1LtfieldInt     int `valid:"ltfield=Field2LtfieldInt"`
	Field2LtfieldInt     int
	Field1LtfieldInt8    int8 `valid:"ltfield=Field2LtfieldInt8"`
	Field2LtfieldInt8    int8
	Field1LtfieldInt16   int16 `valid:"ltfield=Field2LtfieldInt16"`
	Field2LtfieldInt16   int16
	Field1LtfieldInt32   int32 `valid:"ltfield=Field2LtfieldInt32"`
	Field2LtfieldInt32   int32
	Field1LtfieldInt64   int64 `valid:"ltfield=Field2LtfieldInt64"`
	Field2LtfieldInt64   int64
	Field1LtfieldUint    uint `valid:"ltfield=Field2LtfieldUint"`
	Field2LtfieldUint    uint
	Field1LtfieldUint8   uint8 `valid:"ltfield=Field2LtfieldUint8"`
	Field2LtfieldUint8   uint8
	Field1LtfieldUint16  uint16 `valid:"ltfield=Field2LtfieldUint16"`
	Field2LtfieldUint16  uint16
	Field1LtfieldUint32  uint32 `valid:"ltfield=Field2LtfieldUint32"`
	Field2LtfieldUint32  uint32
	Field1LtfieldUint64  uint64 `valid:"ltfield=Field2LtfieldUint64"`
	Field2LtfieldUint64  uint64
	Field1LtfieldFloat32 float32 `valid:"ltfield=Field2LtfieldFloat32"`
	Field2LtfieldFloat32 float32
	Field1LtfieldFloat64 float64 `valid:"ltfield=Field2LtfieldFloat64"`
	Field2LtfieldFloat64 float64
}

func ltfieldStructFieldsTests() {
	log.Println("starting ltfieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &ltfieldStructFields{}
	expectedMsgErrors = []string{
		"Field1LtfieldInt must be < Field2LtfieldInt",
		"Field1LtfieldInt8 must be < Field2LtfieldInt8",
		"Field1LtfieldInt16 must be < Field2LtfieldInt16",
		"Field1LtfieldInt32 must be < Field2LtfieldInt32",
		"Field1LtfieldInt64 must be < Field2LtfieldInt64",
		"Field1LtfieldUint must be < Field2LtfieldUint",
		"Field1LtfieldUint8 must be < Field2LtfieldUint8",
		"Field1LtfieldUint16 must be < Field2LtfieldUint16",
		"Field1LtfieldUint32 must be < Field2LtfieldUint32",
		"Field1LtfieldUint64 must be < Field2LtfieldUint64",
		"Field1LtfieldFloat32 must be < Field2LtfieldFloat32",
		"Field1LtfieldFloat64 must be < Field2LtfieldFloat64",
	}

	v.Field1LtfieldInt = 33
	v.Field1LtfieldInt8 = 33
	v.Field1LtfieldInt16 = 33
	v.Field1LtfieldInt32 = 33
	v.Field1LtfieldInt64 = 33
	v.Field1LtfieldUint = 33
	v.Field1LtfieldUint8 = 33
	v.Field1LtfieldUint16 = 33
	v.Field1LtfieldUint32 = 33
	v.Field1LtfieldUint64 = 33
	v.Field1LtfieldFloat32 = 12.35
	v.Field1LtfieldFloat64 = 12.35

	errs = ltfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &ltfieldStructFields{}
	v.Field1LtfieldInt = 31
	v.Field1LtfieldInt8 = 31
	v.Field1LtfieldInt16 = 31
	v.Field1LtfieldInt32 = 31
	v.Field1LtfieldInt64 = 31
	v.Field1LtfieldUint = 31
	v.Field1LtfieldUint8 = 31
	v.Field1LtfieldUint16 = 31
	v.Field1LtfieldUint32 = 31
	v.Field1LtfieldUint64 = 31
	v.Field1LtfieldFloat32 = 12.33
	v.Field1LtfieldFloat64 = 12.33

	expectedMsgErrors = nil
	errs = ltfieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("ltfieldStructFields types tests ok")
}

type ltefieldStructFields struct {
	Field1LtefieldInt     int `valid:"ltefield=Field2LtefieldInt"`
	Field2LtefieldInt     int
	Field1LtefieldInt8    int8 `valid:"ltefield=Field2LtefieldInt8"`
	Field2LtefieldInt8    int8
	Field1LtefieldInt16   int16 `valid:"ltefield=Field2LtefieldInt16"`
	Field2LtefieldInt16   int16
	Field1LtefieldInt32   int32 `valid:"ltefield=Field2LtefieldInt32"`
	Field2LtefieldInt32   int32
	Field1LtefieldInt64   int64 `valid:"ltefield=Field2LtefieldInt64"`
	Field2LtefieldInt64   int64
	Field1LtefieldUint    uint `valid:"ltefield=Field2LtefieldUint"`
	Field2LtefieldUint    uint
	Field1LtefieldUint8   uint8 `valid:"ltefield=Field2LtefieldUint8"`
	Field2LtefieldUint8   uint8
	Field1LtefieldUint16  uint16 `valid:"ltefield=Field2LtefieldUint16"`
	Field2LtefieldUint16  uint16
	Field1LtefieldUint32  uint32 `valid:"ltefield=Field2LtefieldUint32"`
	Field2LtefieldUint32  uint32
	Field1LtefieldUint64  uint64 `valid:"ltefield=Field2LtefieldUint64"`
	Field2LtefieldUint64  uint64
	Field1LtefieldFloat32 float32 `valid:"ltefield=Field2LtefieldFloat32"`
	Field2LtefieldFloat32 float32
	Field1LtefieldFloat64 float64 `valid:"ltefield=Field2LtefieldFloat64"`
	Field2LtefieldFloat64 float64
}

func ltefieldStructFieldsTests() {
	log.Println("starting ltefieldStructFields types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &ltefieldStructFields{}
	expectedMsgErrors = []string{
		"Field1LtefieldInt must be <= Field2LtefieldInt",
		"Field1LtefieldInt8 must be <= Field2LtefieldInt8",
		"Field1LtefieldInt16 must be <= Field2LtefieldInt16",
		"Field1LtefieldInt32 must be <= Field2LtefieldInt32",
		"Field1LtefieldInt64 must be <= Field2LtefieldInt64",
		"Field1LtefieldUint must be <= Field2LtefieldUint",
		"Field1LtefieldUint8 must be <= Field2LtefieldUint8",
		"Field1LtefieldUint16 must be <= Field2LtefieldUint16",
		"Field1LtefieldUint32 must be <= Field2LtefieldUint32",
		"Field1LtefieldUint64 must be <= Field2LtefieldUint64",
		"Field1LtefieldFloat32 must be <= Field2LtefieldFloat32",
		"Field1LtefieldFloat64 must be <= Field2LtefieldFloat64",
	}

	v.Field1LtefieldInt = 33
	v.Field1LtefieldInt8 = 33
	v.Field1LtefieldInt16 = 33
	v.Field1LtefieldInt32 = 33
	v.Field1LtefieldInt64 = 33
	v.Field1LtefieldUint = 33
	v.Field1LtefieldUint8 = 33
	v.Field1LtefieldUint16 = 33
	v.Field1LtefieldUint32 = 33
	v.Field1LtefieldUint64 = 33
	v.Field1LtefieldFloat32 = 12.35
	v.Field1LtefieldFloat64 = 12.35

	errs = ltefieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &ltefieldStructFields{}
	v.Field1LtefieldInt = 32
	v.Field1LtefieldInt8 = 32
	v.Field1LtefieldInt16 = 32
	v.Field1LtefieldInt32 = 32
	v.Field1LtefieldInt64 = 32
	v.Field1LtefieldUint = 32
	v.Field1LtefieldUint8 = 32
	v.Field1LtefieldUint16 = 32
	v.Field1LtefieldUint32 = 32
	v.Field1LtefieldUint64 = 32
	v.Field1LtefieldFloat32 = 12.34
	v.Field1LtefieldFloat64 = 12.34

	expectedMsgErrors = nil
	errs = ltefieldStructFieldsValidate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("ltefieldStructFields types tests ok")
}
