// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func SliceStringValidate(obj *SliceString) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(len(obj.TypesRequired) > 0) {
		errs = append(errs, types.NewValidationError("TypesRequired must not be empty"))
	}

	return errs
}
