// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func SliceStringValidate(obj *SliceString) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(len(obj.TypesRequired) > 0) {
		errs = append(errs, types.NewValidationError("TypesRequired must not be empty"))
	}

	if !(len(obj.TypesMin) >= 2) {
		errs = append(errs, types.NewValidationError("TypesMin must have at least 2 elements"))
	}

	if !(len(obj.TypesMax) <= 5) {
		errs = append(errs, types.NewValidationError("TypesMax must have at most 5 elements"))
	}

	if !(len(obj.TypesLen) == 3) {
		errs = append(errs, types.NewValidationError("TypesLen must have exactly 3 elements"))
	}

	return errs
}
