// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func StringTypeValidate(obj *StringType) []error {
	var errs []error

	if !(obj.FieldReq != "") {
		errs = append(errs, types.NewValidationError("FieldReq is required"))
	}

	if !(obj.FieldEq == "aabbcc") {
		errs = append(errs, types.NewValidationError("FieldEq must be equal to 'aabbcc'"))
	}

	if !(types.ToLower(obj.FieldEqIC) == "yes") {
		errs = append(errs, types.NewValidationError("FieldEqIC must be equal to 'yes'"))
	}

	if !(len(obj.FieldMinMax) >= 5) {
		errs = append(errs, types.NewValidationError("FieldMinMax length must be >= 5"))
	}

	if !(len(obj.FieldMinMax) <= 10) {
		errs = append(errs, types.NewValidationError("FieldMinMax length must be <= 10"))
	}

	if !(len(obj.FieldLen) == 8) {
		errs = append(errs, types.NewValidationError("FieldLen length must be 8"))
	}

	if !(obj.FieldNeq != "cba") {
		errs = append(errs, types.NewValidationError("FieldNeq must not be equal to 'cba'"))
	}

	if !(types.ToLower(obj.FieldNeqIC) != "yes") {
		errs = append(errs, types.NewValidationError("FieldNeqIC must not be equal to 'yes'"))
	}

	if !(obj.FieldIn == "ab" || obj.FieldIn == "bc" || obj.FieldIn == "cd") {
		errs = append(errs, types.NewValidationError("FieldIn must be one of 'ab' 'bc' 'cd'"))
	}

	if !(obj.EmailReq != "") {
		errs = append(errs, types.NewValidationError("EmailReq is required"))
	}

	if !(types.IsValidEmail(obj.EmailReq) == true) {
		errs = append(errs, types.NewValidationError("EmailReq must be a valid email"))
	}

	if !(types.IsValidEmail(obj.EmailOpt) == true) {
		errs = append(errs, types.NewValidationError("EmailOpt must be a valid email"))
	}

	return errs
}
