// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func StringTypeValidate(obj *StringType) []error {
	var errs []error

	if !(obj.FieldReq != "") {
		errs = append(errs, types.NewValidationError("FieldReq required"))
	}

	if !(types.ToLower(obj.FieldEqIC) == "yes") {
		errs = append(errs, types.NewValidationError("FieldEqIC must be equal to 'yes'"))
	}

	if !(len(obj.FieldGteLte) >= 5) {
		errs = append(errs, types.NewValidationError("length FieldGteLte must be >= 5"))
	}

	if !(len(obj.FieldGteLte) <= 10) {
		errs = append(errs, types.NewValidationError("length FieldGteLte must be <= 10"))
	}

	return errs
}
