// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func StringTypeValidate(obj *StringType) []error {
	var errs []error

	if !(obj.FieldReq != "") {
		errs = append(errs, types.NewValidationError("FieldReq required"))
	}

	if !(obj.FieldEq == "aabbcc") {
		errs = append(errs, types.NewValidationError("FieldEq must be equal to 'aabbcc'"))
	}

	if !(types.ToLower(obj.FieldEqIC) == "yes") {
		errs = append(errs, types.NewValidationError("FieldEqIC must be equal to 'yes'"))
	}

	if !(len(obj.FieldMinMax) >= 5) {
		errs = append(errs, types.NewValidationError("FieldMinMax length must be >= 5"))
	}

	if !(len(obj.FieldMinMax) <= 10) {
		errs = append(errs, types.NewValidationError("FieldMinMax length must be <= 10"))
	}

	if !(len(obj.FieldLen) == 8) {
		errs = append(errs, types.NewValidationError("FieldLen length must be 8"))
	}

	return errs
}
