// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
	"github.com/opencodeco/validgen/tests/endtoend/structsinpkg"
)

func UserWithStructInPkgValidate(obj *UserWithStructInPkg) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.Age >= 18) {
		errs = append(errs, types.NewValidationError("Age must be >= 18"))
	}

	if !(obj.Age <= 130) {
		errs = append(errs, types.NewValidationError("Age must be <= 130"))
	}

	errs = append(errs, structsinpkg.AddressValidate(&obj.Address)...)

	return errs
}
