// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package main

import (
	"encoding/json"
	"errors"

	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error
	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}
	if !(obj.LastName != "") {
		errs = append(errs, types.NewValidationError("LastName is required"))
	}
	if !(obj.Age >= 18) {
		errs = append(errs, types.NewValidationError("Age must be >= 18"))
	}
	return errs
}
func (obj *User) UnmarshalJSON(b []byte) error {
	type alias User
	if err := json.Unmarshal(b, (*alias)(obj)); err != nil {
		return err
	}
	if errs := UserValidate(obj); len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}
