// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package commonexample

import (
	"github.com/opencodeco/validgen/types"
)

func AddressValidate(obj *Address) []error {
	var errs []error
	if !(obj.Street != "") {
		errs = append(errs, types.NewValidationError("Street is required"))
	}
	if !(obj.City != "") {
		errs = append(errs, types.NewValidationError("City is required"))
	}
	if !(obj.Planet != "") {
		errs = append(errs, types.NewValidationError("Planet is required"))
	}
	if !(obj.Phone != "") {
		errs = append(errs, types.NewValidationError("Phone is required"))
	}
	return errs
}
func PaletteValidate(obj *Palette) []error {
	var errs []error
	for _, elem1 := range obj.Colors {
		if !(types.IsColor(elem1)) {
			errs = append(errs, types.NewValidationError("Colors must be a valid color"))
		}
	}
	for _, elem1 := range obj.Labels {
		if !(elem1 == "red" || elem1 == "green" || elem1 == "blue") {
			errs = append(errs, types.NewValidationError("Labels must be one of 'red' 'green' 'blue'"))
		}
	}
	return errs
}
func UserValidate(obj *User) []error {
	var errs []error
	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}
	if !(obj.LastName != "") {
		errs = append(errs, types.NewValidationError("LastName is required"))
	}
	if !(obj.Age >= 0) {
		errs = append(errs, types.NewValidationError("Age must be >= 0"))
	}
	if !(obj.Age <= 130) {
		errs = append(errs, types.NewValidationError("Age must be <= 130"))
	}
	if !(obj.Email != "") {
		errs = append(errs, types.NewValidationError("Email is required"))
	}
	if !(types.IsValidEmail(obj.Email)) {
		errs = append(errs, types.NewValidationError("Email must be a valid email"))
	}
	if !(obj.Gender == "male" || obj.Gender == "female" || obj.Gender == "prefer_not_to") {
		errs = append(errs, types.NewValidationError("Gender must be one of 'male' 'female' 'prefer_not_to'"))
	}
	if !(types.IsColor(obj.FavouriteColor)) {
		errs = append(errs, types.NewValidationError("FavouriteColor must be a valid color"))
	}
	if !(len(obj.Addresses) != 0) {
		errs = append(errs, types.NewValidationError("Addresses must not be empty"))
	}
	for _, elem1 := range obj.Addresses {
		if !(elem1 != nil) {
			errs = append(errs, types.NewValidationError("Addresses is required"))
		}
		if elem1 != nil {
			errs = append(errs, AddressValidate(elem1)...)
		}
	}
	return errs
}
