package pkgwriter

import (
	"testing"

	"github.com/opencodeco/validgen/internal/analyzer"
	"github.com/opencodeco/validgen/internal/codegenerator"
	"github.com/opencodeco/validgen/internal/parser"
	"github.com/sergi/go-diff/diffmatchpatch"
)

func TestBuildFileValidator(t *testing.T) {
	type fields struct {
		Struct *codegenerator.Struct
	}
	tests := []struct {
		name   string
		fields fields
		want   string
	}{
		{
			name: "Valid struct",
			fields: fields{
				Struct: &codegenerator.Struct{
					Struct: &analyzer.Struct{
						Struct: parser.Struct{
							PackageName: "main",

							StructName: "User",
							Fields: []parser.Field{
								{
									FieldName: "FirstName",
									Type:      "string",
									Tag:       `validate:"required"`,
								},
								{
									FieldName: "MyAge",
									Type:      "uint8",
									Tag:       `validate:"required"`,
								},
							},
						},
					},
					ValidatorFuncCode: `
func UserValidate(obj *User) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.MyAge != 0) {
		errs = append(errs, types.NewValidationError("MyAge is required"))
	}

	return errs
}`,
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.MyAge != 0) {
		errs = append(errs, types.NewValidationError("MyAge is required"))
	}

	return errs
}`,
		},
		{
			name: "FirstName must have 5 characters or more",
			fields: fields{
				Struct: &codegenerator.Struct{
					Struct: &analyzer.Struct{
						Struct: parser.Struct{
							PackageName: "main",
							StructName:  "User",
							Fields: []parser.Field{
								{
									FieldName: "FirstName",
									Type:      "string",
									Tag:       `validate:"min=5"`,
								},
							},
						},
					},
					ValidatorFuncCode: `
func UserValidate(obj *User) []error {
	var errs []error

	if !(len(obj.FirstName) >= 5) {
		errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
	}

	return errs
}`,
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(len(obj.FirstName) >= 5) {
		errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
	}

	return errs
}`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := BuildFileValidatorCode(&codegenerator.Pkg{
				Name:    tt.fields.Struct.PackageName,
				Imports: tt.fields.Struct.Imports,
				Structs: map[string]*codegenerator.Struct{
					tt.fields.Struct.StructName: tt.fields.Struct,
				},
			})

			if err != nil {
				t.Errorf("FileValidator.BuildFileValidatorCode() error = %v, wantErr %v", err, nil)
				return
			}

			if got != tt.want {
				t.Errorf("FileValidator.BuildFileValidatorCode() = %v, want %v", got, tt.want)
				dmp := diffmatchpatch.New()
				diffs := dmp.DiffMain(tt.want, got, false)
				if len(diffs) > 1 {
					t.Errorf("FileValidator.BuildFileValidatorCode() diff = \n%v", dmp.DiffPrettyText(diffs))
				}
			}
		})
	}
}
