package pkgwriter

import (
	"regexp"
	"strings"
	"testing"

	"github.com/opencodeco/validgen/internal/analyzer"
	"github.com/opencodeco/validgen/internal/codegenerator"
	"github.com/opencodeco/validgen/internal/common"
	"github.com/opencodeco/validgen/internal/parser"
	"github.com/sergi/go-diff/diffmatchpatch"
)

// Matches the Go generated-file convention used by golangci-lint (strict mode)
// and staticcheck: https://go.dev/s/generatedcode
var generatedFileHeaderRE = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT\.$`)

func TestGeneratedFileHeaderSilencesLinters(t *testing.T) {
	got, err := BuildFileValidatorCode(&codegenerator.Pkg{
		Name: "main",
		Structs: map[string]*codegenerator.Struct{
			"User": {
				Struct: &analyzer.Struct{
					Struct: parser.Struct{
						PackageName: "main",
						StructName:  "User",
					},
				},
				ValidatorFuncCode: `
func UserValidate(obj *User) []error {
return nil
}`,
			},
		},
	})
	if err != nil {
		t.Fatalf("BuildFileValidatorCode() error = %v", err)
	}

	if !generatedFileHeaderRE.MatchString(got) {
		t.Fatalf("generated output missing Go generated-file header; got:\n%s", got)
	}
	if !strings.Contains(got, "//nolint:all\npackage ") {
		t.Fatalf("generated output missing file-level //nolint:all before package; got:\n%s", got)
	}
	if !strings.HasPrefix(got, "// Code generated by ValidGen. DO NOT EDIT.\n\n//nolint:all\npackage ") {
		t.Fatalf("generated header order mismatch; got:\n%s", got)
	}
}

func TestBuildFileValidator(t *testing.T) {
	type fields struct {
		Struct *codegenerator.Struct
	}
	tests := []struct {
		name   string
		fields fields
		want   string
	}{
		{
			name: "Valid struct",
			fields: fields{
				Struct: &codegenerator.Struct{
					Struct: &analyzer.Struct{
						Struct: parser.Struct{
							PackageName: "main",

							StructName: "User",
							Fields: []parser.Field{
								{
									FieldName: "FirstName",
									Type:      common.FieldType{BaseType: "string"},
									Tag:       `validate:"required"`,
								},
								{
									FieldName: "MyAge",
									Type:      common.FieldType{BaseType: "uint8"},
									Tag:       `validate:"required"`,
								},
							},
						},
					},
					ValidatorFuncCode: `
func UserValidate(obj *User) []error {
var errs []error
if !(obj.FirstName != "") {
errs = append(errs, types.NewValidationError("FirstName is required"))
}
if !(obj.MyAge != 0) {
errs = append(errs, types.NewValidationError("MyAge is required"))
}
return errs
}`,
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error
	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}
	if !(obj.MyAge != 0) {
		errs = append(errs, types.NewValidationError("MyAge is required"))
	}
	return errs
}
`,
		},
		{
			name: "FirstName must have 5 characters or more",
			fields: fields{
				Struct: &codegenerator.Struct{
					Struct: &analyzer.Struct{
						Struct: parser.Struct{
							PackageName: "main",
							StructName:  "User",
							Fields: []parser.Field{
								{
									FieldName: "FirstName",
									Type:      common.FieldType{BaseType: "string"},
									Tag:       `validate:"min=5"`,
								},
							},
						},
					},
					ValidatorFuncCode: `
func UserValidate(obj *User) []error {
var errs []error
if !(len(obj.FirstName) >= 5) {
errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
}
return errs
}`,
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error
	if !(len(obj.FirstName) >= 5) {
		errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
	}
	return errs
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := BuildFileValidatorCode(&codegenerator.Pkg{
				Name:    tt.fields.Struct.PackageName,
				Imports: tt.fields.Struct.Imports,
				Structs: map[string]*codegenerator.Struct{
					tt.fields.Struct.StructName: tt.fields.Struct,
				},
			})

			if err != nil {
				t.Errorf("FileValidator.BuildFileValidatorCode() error = %v, wantErr %v", err, nil)
				return
			}

			if got != tt.want {
				t.Errorf("FileValidator.BuildFileValidatorCode() = %v, want %v", got, tt.want)
				dmp := diffmatchpatch.New()
				diffs := dmp.DiffMain(tt.want, got, false)
				if len(diffs) > 1 {
					t.Errorf("FileValidator.BuildFileValidatorCode() diff = \n%v", dmp.DiffPrettyText(diffs))
				}
			}
		})
	}
}

func TestBuildFileValidatorWithUnmarshalJSON(t *testing.T) {
	got, err := BuildFileValidatorCode(&codegenerator.Pkg{
		Name: "main",
		Structs: map[string]*codegenerator.Struct{
			"User": {
				Struct: &analyzer.Struct{
					Struct: parser.Struct{
						PackageName: "main",
						StructName:  "User",
					},
				},
				ValidatorFuncCode: `
func UserValidate(obj *User) []error {
var errs []error
if !(obj.FirstName != "") {
errs = append(errs, types.NewValidationError("FirstName is required"))
}
return errs
}
`,
				UnmarshalJSONCode: `func (obj *User) UnmarshalJSON(b []byte) error {
	type alias User
	if err := json.Unmarshal(b, (*alias)(obj)); err != nil {
		return err
	}
	if errs := UserValidate(obj); len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}
`,
			},
		},
	})
	if err != nil {
		t.Fatalf("BuildFileValidatorCode() error = %v", err)
	}

	want := `// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package main

import (
	"encoding/json"
	"errors"

	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error
	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}
	return errs
}
func (obj *User) UnmarshalJSON(b []byte) error {
	type alias User
	if err := json.Unmarshal(b, (*alias)(obj)); err != nil {
		return err
	}
	if errs := UserValidate(obj); len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}
`
	if got != want {
		dmp := diffmatchpatch.New()
		t.Errorf("BuildFileValidatorCode() diff =\n%s", dmp.DiffPrettyText(dmp.DiffMain(want, got, false)))
	}
}

func TestBuildFileValidatorImportsStringsForEqualFold(t *testing.T) {
	got, err := BuildFileValidatorCode(&codegenerator.Pkg{
		Name: "main",
		Structs: map[string]*codegenerator.Struct{
			"User": {
				Struct: &analyzer.Struct{
					Struct: parser.Struct{
						PackageName: "main",
						StructName:  "User",
					},
				},
				ValidatorFuncCode: `
func UserValidate(obj *User) []error {
var errs []error
if !(strings.EqualFold(obj.Name, "abc")) {
errs = append(errs, types.NewValidationError("Name must be equal to 'abc'"))
}
return errs
}`,
			},
		},
	})
	if err != nil {
		t.Fatalf("BuildFileValidatorCode() error = %v", err)
	}

	want := `// Code generated by ValidGen. DO NOT EDIT.

//nolint:all
package main

import (
	"strings"

	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error
	if !(strings.EqualFold(obj.Name, "abc")) {
		errs = append(errs, types.NewValidationError("Name must be equal to 'abc'"))
	}
	return errs
}
`
	if got != want {
		dmp := diffmatchpatch.New()
		t.Errorf("BuildFileValidatorCode() diff =\n%s", dmp.DiffPrettyText(dmp.DiffMain(want, got, false)))
	}
}
