name: Feature request
description: Suggest an idea for validgen
title: Feature request
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request for ValidGen.
        Please provide as much information as possible. Fields marked with an asterisk (*) are required.

  - type: checkboxes
    id: read_contributing
    attributes:
      label: Pre-check
      options:
        - label: I have read the [Contributing guide](../CONTRIBUTING.md)
          required: true

  - type: checkboxes
    id: read_validation_table
    attributes:
      label: Pre-check
      options:
        - label: I have checked the [Validation Table](../README.md#validations-table)
          required: true

  - type: checkboxes
    id: check_duplicates
    attributes:
      label: Check for existing feature requests
      options:
        - label: I have searched for duplicate or similar feature requests in the [issue tracker](https://github.com/opencodeco/validgen/issues).
          required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed feature
      description: Describe clearly what you would like ValidGen to do.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references that may help.
    validations:
      required: false
