package integration

import (
	"testing"

	"github.com/opencodeco/validgen/internal/codegenerator"
	"github.com/opencodeco/validgen/internal/parser"
	"github.com/sergi/go-diff/diffmatchpatch"
)

func TestIntegrationTests(t *testing.T) {
	type fields struct {
		Struct *parser.Struct
	}
	tests := []struct {
		name    string
		fields  fields
		want    string
		wantErr bool
	}{
		{
			name: "Valid struct",
			fields: fields{
				Struct: &parser.Struct{
					StructParserInfo: parser.StructParserInfo{
						PackageName: "main",
						StructName:  "User",
						Fields: []parser.Field{
							{
								FieldParserInfo: parser.FieldParserInfo{
									FieldName: "FirstName",
									Type:      "string",
									Tag:       `validate:"required"`,
								},
								AnalyzerInfo: parser.AnalyzerInfo{
									Validations: []string{"required"},
								},
							},
							{
								FieldParserInfo: parser.FieldParserInfo{
									FieldName: "MyAge",
									Type:      "uint8",
									Tag:       `validate:"required"`,
								},
								AnalyzerInfo: parser.AnalyzerInfo{
									Validations: []string{"required"},
								},
							},
						},
					},
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.MyAge != 0) {
		errs = append(errs, types.NewValidationError("MyAge is required"))
	}

	return errs
}
`,
			wantErr: false,
		},
		{
			name: "FirstName must have 5 characters or more",
			fields: fields{
				Struct: &parser.Struct{
					StructParserInfo: parser.StructParserInfo{
						PackageName: "main",
						StructName:  "User",
						Fields: []parser.Field{
							{
								FieldParserInfo: parser.FieldParserInfo{
									FieldName: "FirstName",
									Type:      "string",
									Tag:       `validate:"min=5"`,
								},
								AnalyzerInfo: parser.AnalyzerInfo{
									Validations: []string{"min=5"},
								},
							},
						},
					},
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(len(obj.FirstName) >= 5) {
		errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
	}

	return errs
}
`,
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := codegenerator.BuildValidatorCode(tt.fields.Struct)
			if (err != nil) != tt.wantErr {
				t.Errorf("FileValidator.GenerateValidator() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("FileValidator.GenerateValidator() = %v, want %v", got, tt.want)
				dmp := diffmatchpatch.New()
				diffs := dmp.DiffMain(tt.want, got, false)
				if len(diffs) > 1 {
					t.Errorf("FileValidator.GenerateValidator() diff = \n%v", dmp.DiffPrettyText(diffs))
				}
			}
		})
	}
}
