package validgen

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

const (
	IGNORE_CASE_TAG = "ignore_case"
)

var structValidatorTpl = `// Code generated by ValidGen. DO NOT EDIT.

package {{.PackageName}}

import (
	"github.com/opencodeco/validgen/types"
)

func {{.Name}}Validate(obj *{{.Name}}) []error {
	var errs []error
{{range .FieldsInfo}}{{condition .Name .Type .Validations}}{{end}}
	return errs
}
`

type StructInfo struct {
	Name           string
	Path           string
	PackageName    string
	FieldsInfo     []FieldInfo
	HasValidateTag bool
}

// TODO: NewFieldInfo to validate params and build the object.
type FieldInfo struct {
	Name        string
	Type        string
	Tag         string
	Validations []string
}

type FieldTestElements struct {
	loperand     string
	operator     string
	roperand     string
	errorMessage string
}

func (fv *StructInfo) GenerateValidator() (string, error) {
	funcMap := template.FuncMap{
		"condition": condition,
	}

	tmpl, err := template.New("FileValidator").Funcs(funcMap).Parse(structValidatorTpl)
	if err != nil {
		return "", err
	}

	code := new(bytes.Buffer)
	if err := tmpl.Execute(code, fv); err != nil {
		return "", err
	}

	return code.String(), nil
}

func condition(fieldName, fieldType string, fieldValidations []string) (string, error) {

	tests := ""
	for _, fieldValidation := range fieldValidations {
		testCode, err := IfCode(fieldName, fieldValidation, fieldType)
		if err != nil {
			return "", err
		}

		tests += testCode
	}

	return tests, nil
}

func IfCode(fieldName, fieldValidation, fieldType string) (string, error) {
	testElements, err := GetFieldTestElements(fieldName, fieldValidation, fieldType)
	if err != nil {
		return "", fmt.Errorf("field %s: %w", fieldName, err)
	}

	return fmt.Sprintf(
		`
	if !(%s %s %s) {
		errs = append(errs, types.NewValidationError("%s"))
	}
`, testElements.loperand, testElements.operator, testElements.roperand, testElements.errorMessage), nil
}

func GetFieldTestElements(fieldName, fieldValidation, fieldType string) (FieldTestElements, error) {
	ifCode := map[string]FieldTestElements{
		"eq,string":             {"{{.Name}}", "==", `"{{.Target}}"`, "{{.Name}} must be equal to '{{.Target}}'"},
		"required,string":       {"{{.Name}}", "!=", `""`, "{{.Name}} required"},
		"required,uint8":        {"{{.Name}}", "!=", `0`, "{{.Name}} required"},
		"gte,uint8":             {"{{.Name}}", ">=", `{{.Target}}`, "{{.Name}} must be >= {{.Target}}"},
		"lte,uint8":             {"{{.Name}}", "<=", `{{.Target}}`, "{{.Name}} must be <= {{.Target}}"},
		"gte,string":            {"len({{.Name}})", ">=", `{{.Target}}`, "{{.Name}} length must be >= {{.Target}}"},
		"lte,string":            {"len({{.Name}})", "<=", `{{.Target}}`, "{{.Name}} length must be <= {{.Target}}"},
		"eq_ignore_case,string": {"types.ToLower({{.Name}})", "==", `"{{.Target}}"`, "{{.Name}} must be equal to '{{.Target}}'"},
	}

	splitField := strings.Split(fieldValidation, "=")
	validation := splitField[0]
	target := ""
	if len(splitField) > 1 {
		target = splitField[1]
	}

	ifData, ok := ifCode[validation+","+fieldType]
	if !ok {
		return FieldTestElements{}, fmt.Errorf("unsupported validation %s type %s", fieldValidation, fieldType)
	}

	if strings.Contains(validation, IGNORE_CASE_TAG) {
		target = strings.ToLower(target)
	}

	ifData.loperand = strings.ReplaceAll(ifData.loperand, "{{.Name}}", "obj."+fieldName)
	ifData.loperand = strings.ReplaceAll(ifData.loperand, "{{.Target}}", target)
	ifData.roperand = strings.ReplaceAll(ifData.roperand, "{{.Name}}", "obj."+fieldName)
	ifData.roperand = strings.ReplaceAll(ifData.roperand, "{{.Target}}", target)
	ifData.errorMessage = strings.ReplaceAll(ifData.errorMessage, "{{.Name}}", fieldName)
	ifData.errorMessage = strings.ReplaceAll(ifData.errorMessage, "{{.Target}}", target)

	return ifData, nil
}

func (s *StructInfo) GenerateFileValidator() error {
	fmt.Printf("Generating struct %s validations code\n", s.Name)

	code, err := s.GenerateValidator()
	if err != nil {
		return err
	}

	if err := os.WriteFile(s.Path+"/"+strings.ToLower(s.Name)+"_validator.go", []byte(code), 0644); err != nil {
		return err
	}

	return nil
}

func (s *StructInfo) PrintInfo() {
	fmt.Println("Struct:", s.Name)
	fmt.Println("\tHasValidateTag:", s.HasValidateTag)

	for _, f := range s.FieldsInfo {
		fmt.Println("\tField:", f.Name, f.Type, f.Tag)
	}
}
