package validgen

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

var structValidatorTpl = `// Code generated by ValidGen. DO NOT EDIT.

package {{.PackageName}}

import (
	"github.com/opencodeco/validgen/types"
)

func {{.Name}}Validate(obj *{{.Name}}) []error {
	var errs []error
{{range .Fields}}{{condition .Name .Type .Validations}}{{end}}
	return errs
}
`

type Struct struct {
	Name           string
	Path           string
	PackageName    string
	Fields         []Field
	HasValidateTag bool
}

type Field struct {
	Name        string
	Type        string
	Tag         string
	Validations []string
}

func (s *Struct) GenerateValidator() (string, error) {
	funcMap := template.FuncMap{
		"condition": Condition,
	}

	tmpl, err := template.New("FileValidator").Funcs(funcMap).Parse(structValidatorTpl)
	if err != nil {
		return "", err
	}

	code := new(bytes.Buffer)
	if err := tmpl.Execute(code, s); err != nil {
		return "", err
	}

	return code.String(), nil
}

func (s *Struct) GenerateFileValidator() error {
	fmt.Printf("Generating struct %s validations code\n", s.Name)

	code, err := s.GenerateValidator()
	if err != nil {
		return err
	}

	if err := os.WriteFile(s.Path+"/"+strings.ToLower(s.Name)+"_validator.go", []byte(code), 0644); err != nil {
		return err
	}

	return nil
}

func (s *Struct) PrintInfo() {
	fmt.Println("Struct:", s.Name)
	fmt.Println("\tHasValidateTag:", s.HasValidateTag)

	for _, f := range s.Fields {
		fmt.Println("\tField:", f.Name, f.Type, f.Tag)
	}
}
