package codegenerator

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/opencodeco/validgen/internal/parser"
)

var structValidatorTpl = `// Code generated by ValidGen. DO NOT EDIT.

package {{.PackageName}}

import (
{{buildImportPath .Imports .Fields}}
)

func {{.StructName}}Validate(obj *{{.StructName}}) []error {
	var errs []error
{{range .Fields}}{{buildValidationCode .FieldName .Type .Validations}}{{end}}
	return errs
}
`

type structTpl struct {
	StructName  string
	PackageName string
	Fields      []fieldTpl
	Imports     map[string]parser.Import
}

type fieldTpl struct {
	FieldName   string
	Type        string
	Validations []string
}

func (gv *genValidations) BuildValidatorCode() (string, error) {

	stTpl := StructToTpl(gv.Struct)

	funcMap := template.FuncMap{
		"buildImportPath":     gv.buildImportPath,
		"buildValidationCode": gv.buildValidationCode,
	}

	tmpl, err := template.New("FileValidator").Funcs(funcMap).Parse(structValidatorTpl)
	if err != nil {
		return "", err
	}

	code := new(bytes.Buffer)
	if err := tmpl.Execute(code, stTpl); err != nil {
		return "", err
	}

	return code.String(), nil
}

func (gv *genValidations) GenerateFileValidator() error {
	st := gv.Struct

	fmt.Printf("Generating struct %s validations code\n", st.StructName)

	code, err := gv.BuildValidatorCode()
	if err != nil {
		return err
	}

	if err := os.WriteFile(st.Path+"/"+strings.ToLower(st.StructName)+"_validator.go", []byte(code), 0644); err != nil {
		return err
	}

	return nil
}

func (gv *genValidations) buildValidationCode(fieldName, fieldType string, fieldValidations []string) (string, error) {

	tests := ""
	for _, fieldValidation := range fieldValidations {
		var testCode = ""
		var err error

		if IsGoType(fieldType) {
			testCode, err = gv.buildIfCode(fieldName, fieldType, fieldValidation)
			if err != nil {
				return "", err
			}
		} else {
			testCode = gv.buildIfNestedCode(fieldName, fieldType)
		}

		tests += testCode
	}

	return tests, nil
}

func (gv *genValidations) buildIfCode(fieldName, fieldType, fieldValidation string) (string, error) {
	testElements, err := DefineTestElements(fieldName, fieldType, fieldValidation)
	if err != nil {
		return "", fmt.Errorf("field %s: %w", fieldName, err)
	}

	booleanCondition := ""
	for _, roperand := range testElements.rightOperands {
		if booleanCondition != "" {
			booleanCondition += " " + testElements.concatOperator + " "
		}

		booleanCondition += fmt.Sprintf("%s %s %s", testElements.leftOperand, testElements.operator, roperand)
	}

	return fmt.Sprintf(
		`
	if !(%s) {
		errs = append(errs, types.NewValidationError("%s"))
	}
`, booleanCondition, testElements.errorMessage), nil
}

func (gv *genValidations) buildIfNestedCode(fieldName, fieldType string) string {
	_, ok := gv.StructsWithValidation[fieldType]
	if !ok {
		return ""
	}

	pkg := ExtractPackage(fieldType)
	if pkg == gv.Struct.PackageName {
		fieldType = strings.TrimPrefix(fieldType, pkg+".")
	}

	funcName := fieldType + "Validate"
	fieldParam := "&obj." + fieldName

	return fmt.Sprintf(
		`
	errs = append(errs, %s(%s)...)
`, funcName, fieldParam)
}

func (gv *genValidations) buildImportPath(imports map[string]parser.Import, fields []fieldTpl) (string, error) {
	code := ""

	code += "\t\"github.com/opencodeco/validgen/types\""

	for _, field := range fields {
		pkg := ExtractPackage(field.Type)
		if pkg != "" {
			imp, ok := imports[pkg]
			if ok {
				code += fmt.Sprintf("\n\t\"%s\"", imp.Path)
			}
		}
	}

	return code, nil
}
