package codegenerator

import (
	"testing"

	"github.com/opencodeco/validgen/internal/analyzer"
	"github.com/opencodeco/validgen/internal/parser"
	"github.com/sergi/go-diff/diffmatchpatch"
)

func TestIntegrationTests(t *testing.T) {
	type fields struct {
		Struct *analyzer.Struct
	}
	tests := []struct {
		name   string
		fields fields
		want   string
	}{
		{
			name: "Valid struct",
			fields: fields{
				Struct: &analyzer.Struct{
					Struct: parser.Struct{
						PackageName: "main",
						StructName:  "User",
						Fields: []parser.Field{
							{
								FieldName: "FirstName",
								Type:      "string",
								Tag:       `validate:"required"`,
							},
							{
								FieldName: "MyAge",
								Type:      "uint8",
								Tag:       `validate:"required"`,
							},
						},
					},
					FieldsValidations: []analyzer.FieldValidations{
						{
							Validations: []string{"required"},
						},
						{
							Validations: []string{"required"},
						},
					},
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName is required"))
	}

	if !(obj.MyAge != 0) {
		errs = append(errs, types.NewValidationError("MyAge is required"))
	}

	return errs
}
`,
		},
		{
			name: "FirstName must have 5 characters or more",
			fields: fields{
				Struct: &analyzer.Struct{
					Struct: parser.Struct{
						PackageName: "main",
						StructName:  "User",
						Fields: []parser.Field{
							{
								FieldName: "FirstName",
								Type:      "string",
								Tag:       `validate:"min=5"`,
							},
						},
					},
					FieldsValidations: []analyzer.FieldValidations{
						{
							Validations: []string{"min=5"},
						},
					},
				},
			},
			want: `// Code generated by ValidGen. DO NOT EDIT.

package main

import (
	"github.com/opencodeco/validgen/types"
)

func UserValidate(obj *User) []error {
	var errs []error

	if !(len(obj.FirstName) >= 5) {
		errs = append(errs, types.NewValidationError("FirstName length must be >= 5"))
	}

	return errs
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gv := genValidations{
				Struct: tt.fields.Struct,
			}
			got, err := gv.BuildValidatorCode()
			if err != nil {
				t.Errorf("FileValidator.GenerateValidator() error = %v, wantErr %v", err, nil)
				return
			}
			if got != tt.want {
				t.Errorf("FileValidator.GenerateValidator() = %v, want %v", got, tt.want)
				dmp := diffmatchpatch.New()
				diffs := dmp.DiffMain(tt.want, got, false)
				if len(diffs) > 1 {
					t.Errorf("FileValidator.GenerateValidator() diff = \n%v", dmp.DiffPrettyText(diffs))
				}
			}
		})
	}
}
