// Code generated by TestGenerator. DO NOT EDIT.

package main

import "log"

func numericFloatTypeTests() {
	log.Println("starting numeric float tests")

	{{range .FieldTypes}}numeric{{. | title }}Tests()
	{{end}}
	log.Println("numeric float tests ok")
}
{{range .FieldTypes}}
type NumericType{{. | title }} struct {
	FieldReq   {{.}} `valid:"required"`
	FieldEq    {{.}} `valid:"eq=5.9"`
	FieldNeq   {{.}} `valid:"neq=5.9"`
	FieldGt    {{.}} `valid:"gt=10.1"`
	FieldGte   {{.}} `valid:"gte=10.1"`
	FieldLt    {{.}} `valid:"lt=9.9"`
	FieldLte   {{.}} `valid:"lte=9.9"`
	FieldIn    {{.}} `valid:"in=5.1 6.2 7.3"`
	FieldNotIn {{.}} `valid:"nin=8.5 9.6 10.7"`
}

func numeric{{. | title }}Tests() {
	log.Println("starting numeric {{.}} tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios
	v := &NumericType{{. | title }}{
		FieldReq:   0,
		FieldEq:    1.2,
		FieldNeq:   5.9,
		FieldGt:    8.1,
		FieldGte:   8.1,
		FieldLt:    12.2,
		FieldLte:   12.2,
		FieldIn:    3.123,
		FieldNotIn: 9.6,
	}
	expectedMsgErrors = []string{
		"FieldReq is required",
		"FieldEq must be equal to 5.9",
		"FieldNeq must not be equal to 5.9",
		"FieldGt must be > 10.1",
		"FieldGte must be >= 10.1",
		"FieldLt must be < 9.9",
		"FieldLte must be <= 9.9",
		"FieldIn must be one of '5.1' '6.2' '7.3'",
		"FieldNotIn must not be one of '8.5' '9.6' '10.7'",
	}
	errs = NumericType{{. | title }}Validate(v)
	if !expectedMsgErrorsOk(errs, expectedMsgErrors) {
		log.Fatalf("error = %v, wantErr %v", errs, expectedMsgErrors)
	}

	// Test case 2: All valid input
	v = &NumericType{{. | title }}{
		FieldReq:   123,
		FieldEq:    5.9,
		FieldNeq:   2.4,
		FieldGt:    11.1,
		FieldGte:   12.1,
		FieldLt:    9.1,
		FieldLte:   8.1,
		FieldIn:    6.2,
		FieldNotIn: 12.4,
	}
	expectedMsgErrors = nil
	errs = NumericType{{. | title }}Validate(v)
	if !expectedMsgErrorsOk(errs, expectedMsgErrors) {
		log.Fatalf("error = %v, wantErr %v", errs, expectedMsgErrors)
	}

	log.Println("numeric {{.}} tests ok")
}
{{end}}