// Code generated by ValidGen. DO NOT EDIT.

package structsinpkg

import (
	"github.com/opencodeco/validgen/types"
)

func Type1Validate(obj *Type1) []error {
	var errs []error

	if !(obj.FirstName != "") {
		errs = append(errs, types.NewValidationError("FirstName required"))
	}

	if !(obj.LastName != "") {
		errs = append(errs, types.NewValidationError("LastName required"))
	}

	if !(obj.Age != 0) {
		errs = append(errs, types.NewValidationError("Age required"))
	}

	return errs
}
