// Code generated by TestGen. DO NOT EDIT.

package main

import (
	"log"
)

func innerFieldnoPointerTests() {
{{range .TestCases}}{{.StructName}}Tests()
{{end}}
}

{{range .TestCases}}

type {{.StructName}} struct {
	{{range .Tests}}{{.FieldName1}} {{.FieldType}} `valid:"{{.Validation}}"`
	{{.FieldName2}} {{.FieldType}}
	{{end}}
}

func {{.StructName}}Tests() {
	log.Println("starting {{.StructName}} types tests")

	var expectedMsgErrors []string
	var errs []error

	// Test case 1: All failure scenarios (invalid cases)
	v := &{{.StructName}}{}
	expectedMsgErrors = []string{
		{{range .Tests}}"{{.ErrorMessage}}",
		{{end}}
	}

	{{range .Tests}}{{ if ne .InvalidCase "--" }}v.{{.FieldName1}} = {{.InvalidCase}}{{end}}
	{{end}}
	errs = {{.StructName}}Validate(v)
	assertExpectedErrorMsgs("testcase 1", errs, expectedMsgErrors)

	// Test case 2: All valid cases
	v = &{{.StructName}}{}
	{{range .Tests}}v.{{.FieldName1}} = {{.ValidCase}}
	{{end}}
	expectedMsgErrors = nil
	errs = {{.StructName}}Validate(v)
	assertExpectedErrorMsgs("testcase 2", errs, expectedMsgErrors)

	log.Println("{{.StructName}} types tests ok")
}

{{end}}